title: immsswd
email: imamsiswandii at gmail do com
description: >
   a student, random thing, linux, programming, front-end dev, geeks, a guy pretend being an expert.
baseurl: ""
url: "https://immsswd.github.io"
canonical-url: "https://immsswd.github.io"
permalink: /:categories/:title/
excerpt_separator: "\n\n"
footer: true
paginate: 5
paginate_path: "/blog/page:num"
timezone: Asia/Jakarta
# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
#   - Gemfile.lock
#    - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
