title: Imam
email: imamsiswandii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an awesome description for my site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://golbok.github.io" # the base hostname & protocol for your site, e.g. http://example.com
canonical-url: https://golbok.github.io
permalink: /:categories/:title/
excerpt_separator: "\n\n"
footer: true
paginate: 3
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#    - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
