title: immsswd
email: imamsiswandii at gmail do com
description: >
   Computer software and other things.
baseurl: ""
url: "https://immsswd.github.io"
canonical-url: "https://immsswd.github.io"
permalink: /:categories/:title/
excerpt_separator: "\n\n"
footer: true
paginate: 5
paginate_path: "/blog/page:num"
timezone: Asia/Jakarta
google_analytics: ''
image_fulls_loc: "/img/images/fulls"
image_thumbs_loc: "/img/images/thumbs"

collections:
  galls:

#sitemaps
#sitemap: true
# sass:
#   sass_dir: dev/sass
#   style: compressed

future: public_storage/

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#    - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
