title: Notes
author:
  name: Imam
  email: i.mail@tuta.io
baseurl: ""
url: "https://immsswd.github.io"
canonical-url: "https://immsswd.github.io"
# permalink: /:categories/:title/
permalink: /:categories/:year/:month/:day/:title
description: > # this means to ignore newlines until "show_excerpts:"
  Technology and Random things.
show_excerpts: true # set to true to show excerpts on the homepage

lang: ID
paginate: 3
paginate_path: "/_layouts/home:num"

disqus:
  shortname: imam-3 

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  style: "compressed"
minima:
  skin: classic
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: nil
    # github:  nil
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: imamsisw
    linkedin: imam
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: is_bool
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
